import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {createInterface} from 'node:readline';
import http from 'node:http';
const TOKEN='unit-test-token-abcdefghijklmnopqrstuvwxyz';
let child,origin,reader,buffer='',sequence=0;
const headers={'Authorization':`Bearer ${TOKEN}`,'Content-Type':'application/json','Accept':'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25'};
async function start(stdio=false){const process=spawn(globalThis.process.execPath,[new URL('../server/server.mjs',import.meta.url).pathname,'--port','0',...(stdio?['--stdio']:[])],{env:{...globalThis.process.env,PAINT_MCP_TOKEN:TOKEN},stdio:['pipe','pipe','pipe']});let logs='';await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Server did not start.')),5000);process.stderr.on('data',chunk=>{logs+=chunk;const m=logs.match(/MCP endpoint: (http:\/\/127\.0\.0\.1:\d+)\/mcp/);if(m){clearTimeout(timeout);resolve(m[1]);}});process.on('error',reject);process.on('exit',code=>{if(code)reject(new Error(logs));});});const url=logs.match(/MCP endpoint: (http:\/\/127\.0\.0\.1:\d+)\/mcp/)[1];return {process,url};}
async function post(path,body,extra={}){return fetch(origin+path,{method:'POST',headers:{...headers,...extra},body:JSON.stringify(body)});}
async function rpc(method,params={}){const response=await post('/mcp',{jsonrpc:'2.0',id:++sequence,method,params});return {response,body:await response.json()};}
async function event(){for(;;){const at=buffer.indexOf('\n\n');if(at>=0){const text=buffer.slice(0,at);buffer=buffer.slice(at+2);const line=text.split('\n').find(l=>l.startsWith('data: '));if(line)return JSON.parse(line.slice(6));continue;}const {value,done}=await reader.read();if(done)throw new Error('SSE stream ended.');buffer+=new TextDecoder().decode(value);}}
async function connect(id='test-browser-client-123456789'){const r=await post('/bridge/connect',{clientId:id});assert.equal(r.status,200);const stream=await fetch(origin+'/bridge/events?clientId='+id,{headers});assert.equal(stream.status,200);reader=stream.body.getReader();buffer='';assert.equal((await event()).type,'ready');return id;}
before(async()=>{const started=await start();child=started.process;origin=started.url;});
after(async()=>{await reader?.cancel().catch(()=>{});child?.kill('SIGTERM');});
test('serves only app assets and a strict CSP',async()=>{const r=await fetch(origin);assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/script-src 'self'/);assert.match(await r.text(),/Drawing canvas/);for(const path of ['/server/server.mjs','/package.json','/src/%2e%2e%2fserver/server.mjs'])assert.equal((await fetch(origin+path)).status,404);});
test('MCP requires bearer authentication',async()=>{assert.equal((await fetch(origin+'/mcp',{method:'POST',body:'{}'})).status,401);assert.equal((await post('/mcp',{}, {Authorization:'Bearer wrong'})).status,401);});
test('cross-origin requests rejected even with valid token',async()=>{assert.equal((await post('/mcp',{}, {Origin:'https://malicious.example'})).status,403);assert.equal((await post('/bridge/connect',{clientId:'test-client-123456789'}, {Origin:'null'})).status,403);});
test('DNS rebinding host rejected',async()=>{const result=await new Promise((resolve,reject)=>{const r=http.request(origin+'/health',{headers:{Host:'attacker.example'}},res=>{res.resume();resolve(res.statusCode);});r.on('error',reject);r.end();});assert.equal(result,403);});
test('initialize negotiates supported revision and declares tools/resources',async()=>{const r=await rpc('initialize',{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'tests',version:'1'}});assert.equal(r.response.status,200);assert.equal(r.body.result.protocolVersion,'2025-06-18');assert.ok(r.body.result.capabilities.tools);assert.ok(r.body.result.capabilities.resources);});
test('notifications are accepted with empty HTTP 202',async()=>{const r=await post('/mcp',{jsonrpc:'2.0',method:'notifications/initialized'});assert.equal(r.status,202);assert.equal(await r.text(),'');});
test('tool discovery has 17 validated schemas',async()=>{const r=await rpc('tools/list');assert.equal(r.body.result.tools.length,17);assert.ok(r.body.result.tools.find(t=>t.name==='paint_export'));});
test('unpaired browser returns an actionable tool error',async()=>{const r=await rpc('tools/call',{name:'paint_get_state',arguments:{}});assert.equal(r.body.result.isError,true);assert.match(r.body.result.content[0].text,/No authorized Paint tab/);});
test('malformed commands and unknown methods rejected',async()=>{assert.equal((await rpc('tools/call',{name:'paint_new',arguments:{width:0,height:2}})).body.error.code,-32602);assert.equal((await rpc('arbitrary/eval')).body.error.code,-32601);const r=await post('/mcp',[{jsonrpc:'2.0',id:1,method:'ping'}]);assert.equal((await r.json()).error.code,-32600);});
test('stateless GET/DELETE are explicitly not offered',async()=>{assert.equal((await fetch(origin+'/mcp',{headers})).status,405);assert.equal((await fetch(origin+'/mcp',{method:'DELETE',headers})).status,405);});
test('unknown protocol header rejected',async()=>{assert.equal((await post('/mcp',{jsonrpc:'2.0',id:1,method:'ping'},{'MCP-Protocol-Version':'wrong'})).status,400);});
test('authenticated browser SSE receives tool and completes JSON response',async()=>{const id=await connect();const waiting=rpc('tools/call',{name:'paint_get_state',arguments:{}});const task=await event();assert.equal(task.name,'paint_get_state');const r=await post('/bridge/result',{clientId:id,id:task.id,result:{width:640,height:480,tool:'pencil'}});assert.equal(r.status,200);const response=await waiting;assert.equal(response.body.result.structuredContent.width,640);assert.equal(response.body.result.content[0].type,'text');});
test('another browser cannot take over an active tab',async()=>{const r=await post('/bridge/connect',{clientId:'another-test-browser-123456789'});assert.equal(r.status,409);});
test('image tool result is emitted as an MCP image block',async()=>{const waiting=rpc('tools/call',{name:'paint_export',arguments:{format:'png',maxDimension:1024}}),task=await event();await post('/bridge/result',{clientId:'test-browser-client-123456789',id:task.id,result:{mimeType:'image/png',data:'iVBORw0KGgo=',width:1,height:1,name:'test.png'}});const r=await waiting;assert.equal(r.body.result.content[0].type,'image');assert.equal(r.body.result.content[0].mimeType,'image/png');assert.equal(r.body.result.structuredContent.width,1);assert.equal(r.body.result.structuredContent.data,undefined);});
test('resources include live state and a static agent guide',async()=>{const r=await rpc('resources/list');assert.equal(r.body.result.resources.length,2);const guide=await rpc('resources/read',{uri:'paint://guide'});assert.match(guide.body.result.contents[0].text,/not atomic/);});
test('disabling access cancels pending agent requests',async()=>{const waiting=rpc('tools/call',{name:'paint_get_state',arguments:{}});await event();await post('/bridge/disconnect',{clientId:'test-browser-client-123456789'});const r=await waiting;assert.equal(r.body.result.isError,true);assert.match(r.body.result.content[0].text,/disabled/);await reader.cancel();reader=null;});
test('stdio transport writes only JSON-RPC to stdout',async()=>{const {process:proc}=await start(true);const lines=createInterface({input:proc.stdout});const response=once(lines,'line');proc.stdin.write(JSON.stringify({jsonrpc:'2.0',id:8,method:'initialize',params:{protocolVersion:'2025-11-25'}})+'\n');const [line]=await response;const m=JSON.parse(line);assert.equal(m.id,8);assert.equal(m.result.serverInfo.name,'paint-xp-webgpu');const next=once(lines,'line');proc.stdin.write(JSON.stringify({jsonrpc:'2.0',id:9,method:'tools/list'})+'\n');assert.equal(JSON.parse((await next)[0]).result.tools.length,17);proc.kill('SIGTERM');lines.close();});
